# Generated by Django 5.1.4 on 2024-12-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anggota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_anggota', models.CharField(max_length=4)),
                ('nama_anggota', models.TextField()),
                ('tanggal_lahir', models.TextField()),
                ('profesi', models.TextField()),
            ],
        ),
    ]
