# Generated by Django 5.1.4 on 2024-12-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_buku', models.CharField(max_length=4)),
                ('judul_buku', models.TextField()),
                ('pengarang', models.TextField()),
                ('tahun', models.TextField()),
            ],
        ),
    ]
