# Generated by Django 5.1.4 on 2024-12-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buku', '0002_rename_books_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='penerbit',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
