# Generated by Django 5.1.4 on 2024-12-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penerbit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penerbit',
            name='email_penerbit',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='penerbit',
            name='telp_penerbit',
            field=models.TextField(max_length=12),
        ),
    ]
