# Generated by Django 5.1.4 on 2024-12-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_penulis', models.TextField()),
                ('nama_penulis', models.TextField()),
                ('alamat_penulis', models.TextField()),
                ('kota_penulis', models.TextField()),
                ('telp_penulis', models.TextField()),
                ('email_penulis', models.TextField()),
            ],
        ),
    ]
